name: ChatTweaks
version: '1.0'
main: me.junioraww.chattweaks.Main
api-version: '1.21'
commands:
  hud:
    description: Handle hud
    aliases: [h]
  me: {}
  vanish:
    aliases: [v]
permissions:
  tweaks.vip: {}
  tweaks.colors: {}
  tweaks.vanish: {}