name: ChatTweaks
version: '1.0'
main: me.junioraww.chattweaks.Main
api-version: '1.21'
commands:
  hud:
    description: Handle hud
    aliases: [h]
  me: {}
  vanish:
    aliases: [v]
  mute:
    description: Мут игрока
    permission: tweaks.mute
  tell:
    description: Личное сообщение
    aliases: [ w, msg, m, whisper ]
permissions:
  tweaks.vip: {}
  tweaks.colors: {}
  tweaks.vanish: {}
  tweaks.mute: {}
depend: [ LuckPerms ]
softdepend: [ Skingram ]